# Generated by Django 4.2.23 on 2025-09-10 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.CharField(max_length=300, verbose_name='Short Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image')),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies', max_length=500, verbose_name='Technologies')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='Live Demo URL')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='منتظر حازم ثامر', max_length=100, verbose_name='Site Title')),
                ('site_tagline', models.CharField(default='مطور برمجيات – Django & Web', max_length=200, verbose_name='Site Tagline')),
                ('about_text', models.TextField(default='مطور ويب شغوف ببناء تطبيقات نظيفة وقابلة للتوسع.', verbose_name='About Text')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profile Image')),
                ('email', models.EmailField(default='contact@yourdomain.com', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X URL')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('google_analytics_id', models.CharField(blank=True, max_length=20, verbose_name='Google Analytics ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('celebration', 'Celebration'), ('holiday', 'Holiday'), ('mourning', 'Mourning'), ('event', 'Event')], default='info', max_length=20, verbose_name='Type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('show_countdown', models.BooleanField(default=False, verbose_name='Show Countdown')),
                ('is_dismissible', models.BooleanField(default=True, verbose_name='Dismissible')),
                ('show_on_all_pages', models.BooleanField(default=True, verbose_name='Show on All Pages')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('background_color', models.CharField(default='#3B82F6', help_text='Hex color code (e.g., #3B82F6)', max_length=7, verbose_name='Background Color')),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Hex color code (e.g., #FFFFFF)', max_length=7, verbose_name='Text Color')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='Link URL')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Link Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
