# Generated by Django 4.2.23 on 2025-08-22 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('review', markdownx.models.MarkdownxField(blank=True, verbose_name='Review')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='Cover Image')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pages')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Publisher')),
                ('language', models.CharField(default='Arabic', max_length=50, verbose_name='Language')),
                ('status', models.CharField(choices=[('reading', 'Currently Reading'), ('completed', 'Completed'), ('want_to_read', 'Want to Read'), ('abandoned', 'Abandoned')], default='want_to_read', max_length=20, verbose_name='Status')),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True, verbose_name='Rating')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Finish Date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Book Category',
                'verbose_name_plural': 'Book Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('content', markdownx.models.MarkdownxField(verbose_name='Content')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Page Number')),
                ('is_quote', models.BooleanField(default=False, verbose_name='Is Quote')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='books.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Book Note',
                'verbose_name_plural': 'Book Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.bookcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='books_book_created_ea3fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_published'], name='books_book_is_publ_a108dd_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='books_book_slug_ca552e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='books_book_status_ea5e47_idx'),
        ),
    ]
